### PR TITLE
3.0.3 –  Remove hasAlreadyLoaded check to fix configuration bug 

### LINKED ISSUE #89: Problem shouldReplaceImage
I am using 3.0.2, and when I try use **shouldReplaceImage=false** and **zoomImage** together image don't get zoomed second time. 

Expected:

Click to zoom: zoomImage showed.
Click to unzoom: original image showed.

Click to zoom again: zoomImage showed (bit this not works, instead original image showed).

### PR DESCRIPTION
**Pull request by rpearce**
Fixes #89 

cc @alexshelkov

### CODE REVIEW

File: src/Zoom.js [hunk 1]
```diff
@@ -61,7 +61,7 @@ export default class Zoom extends Component {
   _handleImageLoad(img) {
     // Only set state if component is still mounted
     if (this.state.isZoomed) {
-      this.setState({ hasLoaded: true, src: img.currentSrc || img.src })
```
Comment (rpearce) [inline src/Zoom.js]: `hasLoaded: true` is duplicated & unnecessary here, so removed

File: src/Zoom.js [hunk 2]
```diff
@@ -26,11 +26,11 @@ export default class Zoom extends Component {
   }
 
   componentDidMount() {
-    const { hasAlreadyLoaded, zoomImage: { src, srcSet } } = this.props
+    const { zoomImage: { src, srcSet } } = this.props
 
     this.setState({ hasLoaded: true })
 
-    if ((src || srcSet) && !hasAlreadyLoaded) {
+    if (src || srcSet) {
```
Comment (rpearce) [inline src/Zoom.js]: The original thinking with this was that if the image had already been downloaded, then don't bother doing the whole `new Image()` thing again; however, that is _very_ cheap as it fetches from the browser's cached version. 

This is where the bug came from.

If the `Zoom` component had already been zoomed and unzoomed, then the parent component, `ImageZoom` set this arbitrary `hasAlreadyLoaded` property. However, in the case where we _do not replace the original image_ and we _have a zoomImage_, it would prevent the zoomImage from being displayed after the first time.

File: README.md [hunk 3]
```diff
@@ -110,6 +110,7 @@ Thanks goes to these wonderful people ([emoji key](https://github.com/kentcdodds
...
 | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
+| [<img src="https://avatars3.githubusercontent.com/u/1233347?v=4" width="100px;"/><br /><sub>Alex Shelkovskiy</sub>](https://github.com/alexshelkov)<br />[🐛](https://github.com/rpearce/react-medium-image-zoom/issues?q=author%3Aalexshelkov "Bug reports") |
```
Comment (rpearce) [inline README.md]: @alexshelkov this is you being added to our all-contributors list. Thanks for your contribution to the project!
