### PR TITLE
fix firefox flicker #96

### LINKED ISSUE #96: Replacing low-res with downloaded high-res image flickers/flashes on new FireFox
This issue is a: 

- Bug report

## Expected behavior
I expected there to not be a flicker when the the larger image was loaded and replaced the old one.

## Actual behavior
What actually happened: it flickers.

## Steps to reproduce behavior
1. open up the new firefox
1. go to the example page (link below)
1. click the first image (a bridge)

## Link to repository/example of behavior
[link to example](https://rpearce.github.io/react-medium-image-zoom/)

### PR DESCRIPTION
**Pull request by rpearce**
This pull request closes #96 .

@kingdido999: what do you think of this solution? Seems to be good, though I feel _meh_ about adding `100ms` onto the load time. Would you do a Firefox check [here](https://github.com/rpearce/react-medium-image-zoom/pull/117/files#diff-ac72cd8615dec0dd5b0fda073454a248R85)? _Update: I did that Firefox check._

## Pre-Flight Checklist
I have made sure to
- [x] make sure this PR is set to merge to the correct `X-0-stable` branch if it's not going to master
- [x] add a Storybook example (if necessary)
- [x] manually test all the Storybook examples
  * run `$ yarn run storybook`
  * navigate to http://localhost:6006
- [x] run `$ yarn run build` to build the project code & static example
- [x] check that the example in `example/build/index.html` works: `$ open example/build/index.html`

### CODE REVIEW

File: src/Zoom.js [hunk 1]
```diff
@@ -5,14 +5,27 @@ import { fetchImage, getMaxDimensionScale, getScale } from './helpers'
...
+ * The `tmpSrc` and `TmpImg` code here is a workaround
+ * for a longstanding Firefox issue where replacing the
+ * `src` of an `<img>` tag requires calculations and
+ * results in a "flicker" of sorts.
+ *
+ * See https://github.com/rpearce/react-medium-image-zoom/issues/96
+ * for further details.
+ */
+
+const isFirefox = typeof InstallTrigger !== 'undefined'
```
Comment (kingdido999) [inline src/Zoom.js]: Seems [InstallTrigger](https://developer.mozilla.org/en-US/docs/Web/API/InstallTrigger) is not on standard track, which means it might be dropped by Firefox in the future?

**Comment by kingdido999** [comment]
@rpearce  Have you updated the GitHub page with the latest release as well? I still see flickering when it just starts zooming in. My Firefox version is 58.

**Comment by rpearce** [comment]
@kingdido999 I forgot to push to the `gh-pages` branch 🤦‍♂️ . I'm about to make a PR with a `docs/` folder and use that, instead. 

With regards to `InstallTrigger`, after doing some research, it seems to be the only reliable way of detecting Firefox, as it's the API used for Firefox plugins and the existence of it is therefore only in Firefox. I'm open to other suggestions, though.

**Comment by rpearce** [comment]
@kingdido999 https://rpearce.github.io/react-medium-image-zoom/ has been updated and is reading from the `docs/` folder now.

THANK YOU for your thoughts here: they are appreciated.

**Comment by kingdido999** [comment]
@rpearce Fair enough 😄 . Another approach is just to do it for all browsers without feature detection. Since Firefox has moved on to [WebExtensions](https://wiki.mozilla.org/WebExtensions) API to install add-ons, so it's possible they drop the old `InstallTrigger` API in the future.

**Comment by rpearce** [comment]
@kingdido999 well played. I'll think on it a bit more but will ultimately take out `InstallTrigger` for sure.
